### ISSUE TITLE
Instructions for adding binary to $PATH

### ISSUE THREAD

**Issue by kayserifserif** [thesephist/superstat#1]
Hi, I just installed this and I love it!! It's exactly what I need and I can definitely see myself using it a ton for my work :)

I don't know if you would want to include this, but I thought I might write here how I added the binary to my `$PATH`, just in case others need it like I did!

1. Download the pre-built binary on the [releases page](https://github.com/thesephist/superstat/releases)
2. Rename the binary from the download name (e.g. `superstat-macos-arm64`) to just `superstat`
3. Make it executable by running `sudo chmod 755 superstat`
4. Move the binary to somewhere in your `$PATH` like `/usr/local/bin/`
5. Restart Terminal
6. Check that the binary is in your $PATH by running `command -v superstat` – if it says `/usr/local/bin/superstat` (or wherever you moved it to) then you're good to go!

**Comment by thesephist** [comment]
Thanks @whykatherine! I think this is exactly what I did, except that I run `chmod +x superstat`, which is the more literal version of "add the execute permission".

If you feel up for it, would you want to add a more descriptive version of this to the ["Install" section of the README](https://github.com/thesephist/superstat#install) in a PR? If not I'll probably get to it when I find some time on my hands.
